@startuml

!define RECTANGLE class

class "Normal User" as User <<RECTANGLE>>
class "Admin" as Admin <<RECTANGLE>>
class "Company" as Company <<RECTANGLE>>
class "Internship Platform" as InternshipPlatform <<RECTANGLE>>
class "Database" as Database <<RECTANGLE>>

InternshipPlatform --|> Database : Manages
InternshipPlatform --|> User : Manages
InternshipPlatform --|> Admin : Manages
InternshipPlatform --|> Company : Manages

InternshipPlatform : +browseInternships()
InternshipPlatform : +viewInternshipDetails()
InternshipPlatform : +applyForInternship()
InternshipPlatform : +contactAdmin()

Admin : +reviewApplications()
Admin : +acceptOrRejectApplications()
Admin : +reviewInquiries()
Admin : +respondToInquiries()
Admin : +manageInternships()
Admin : +manageUsers()
Admin : +banUserOrCompany()

Company : +createInternshipPrograms()
Company : +reviewApplications()
Company : +contactAdmin()

Database : +retrieveInternshipList()
Database : +retrieveInternshipDetails()
Database : +saveApplication()
Database : +retrieveApplications()
Database : +updateApplicationStatus()
Database : +saveInternshipProgram()
Database : +retrieveInquiryDetails()
Database : +saveInquiry()
Database : +updateUserOrCompanyStatus()

@enduml
