@startuml component
package "Internship System" {
  [User]
  [Admin]
  [Company]
  [Internship]
  [Communication]
  [Database]
  [Application]
}

[User] --> [Admin]
[User] --> [Company]
[Admin] --> [Internship]
[Company] --> [Internship]
[Communication] --> [User]
[Communication] --> [Communication Handler]
[Communication Handler] --> [Notification]
[Communication Handler] --> [Inquiry Resolver]
[Communication Handler] --> [Database]
[Company] --> [Application]
[Admin] --> [Application]
[User] --> [Application]
[Application] --> [Database]
@enduml
