@startuml object

object User {
  id: int
  name: String
  email: String
  cv: File
  applications: List<InternshipApplication>
  inquiries: List<Inquiry>
}

object Admin {
  reviewedApplications: List<InternshipApplication>
  inquiries: List<Inquiry>
}

object Company {
  id: int
  name: String
  programs: List<InternshipProgram>
}

object InternshipProgram {
  id: int
  title: String
  description: String
  company: Company
  applications: List<InternshipApplication>
}

object InternshipApplication {
  id: int
  user: User
  program: InternshipProgram
  status: ApplicationStatus
  applicationDate: Date
}

object Inquiry {
  id: int
  user: User
  subject: String
  message: String
  status: InquiryStatus
  inquiryDate: Date
}

enum ApplicationStatus {
    PENDING, APPROVED, REJECTED
    }

enum InquiryStatus {
    OPEN, CLOSED
}

User --|> InternshipApplication
User --|> Inquiry
Admin --|> InternshipApplication
Admin --|> Inquiry
Company --|> InternshipProgram
Company --|> InternshipApplication
InternshipProgram --|> InternshipApplication
@enduml
