@startuml activity

start
:User Request;

if (Normal User?) then (yes)
  :NormalUser.handleRequest();
  :Browse, Apply, Contact Admin, Submit Inquiry;
  if (Apply for Internship?) then (yes)
    :NormalUser.submitApplication();
    :Receive and Notify Application;
    :Admin: --> (Review Applications);
    if (Review Applications?) then (yes)
      :Admin.processApplications();
      :Accept/Reject and Notify User;
    endif
  endif
  if (Submit Inquiry?) then (yes)
    :NormalUser.submitInquiry();
    :Receive, Review, Provide Details;
    :Admin: --> (Review Inquiries);
    if (Review Inquiries?) then (yes)
      :Admin.respondToInquiry();
      :Notify User: Admin Response/Unavailable;
    endif
  endif
else (Company)
  :Company.handleRequest();
  :Create Program, Contact Admin, Submit Inquiry;
  if (Provide Program Details?) then (yes)
    :Company.createInternshipProgram();
    :Receive and Confirm Program Creation;
    :Notify User: Program Created;
  endif
  if (Contact Admin?) then (yes)
    :Company.submitInquiry();
    :Receive, Review, Provide Details;
    :Admin: --> (Review Inquiries);
    if (Review Inquiries?) then (yes)
      :Admin.respondToInquiry();
      :Notify User: Admin Response/Unavailable;
    endif
  endif
endif

stop
@enduml
