@startuml

actor "Normal User" as user
actor "Admin" as admin
actor "Company" as company

participant "Internship Platform" as platform
participant "Internship Catalog" as catalog
participant "Application Manager" as appManager
participant "Inquiry System" as inquirySystem
participant "Internship Management" as internshipManagement


user -> catalog: Browse Internships
catalog -> user: Display Internship List

user -> catalog: View Internship Details
catalog -> user: Display Internship Details

user -> appManager: Apply for Internships

admin -> appManager: Review Applications
appManager -> admin: Provide Application Details
admin -> appManager: Accept or Reject Applications
appManager -> user: Notify Application Status

admin -> inquirySystem: Respond to Inquiries
inquirySystem -> admin: Display Inquiry Details
admin -> inquirySystem: Save Response
inquirySystem -> user: Notify User

admin -> internshipManagement: Manage Internships
internshipManagement -> admin: Display Internship Management Options

admin -> internshipManagement: Manage Users
internshipManagement -> admin: Display User Management Options

admin -> internshipManagement: Ban User or Company
internshipManagement -> admin: Display Ban Options

company -> internshipManagement: Create Internship Programs
internshipManagement -> company: Display Program Creation Form
company -> appManager: Review Applications
appManager -> company: Provide Application Details
company -> inquirySystem: Contact Admin

@enduml
