@startuml

left to right direction

actor "Normal User" as user
actor "Admin" as admin
actor "Company" as company

rectangle "Internship Platform" {
  usecase "Browse Internships" as browse
  usecase "View Internship Details" as viewDetails
  usecase "Apply for Internships" as apply
  usecase "Contact Admin" as contactAdmin

  admin --> (Review Applications)
  admin --> (Accept or Reject Applications)
  admin --> (Review Inquiries)
  admin --> (Respond to Inquiries)
  admin --> (Manage Internships)
  admin --> (Manage Users)

  user --> browse
  user --> viewDetails
  user --> apply
  user --> contactAdmin

  company --> (Create Internship Programs)
  company --> (Review Applications)
  company --> (Contact Admin)
}

@enduml
